before_install:
- openssl aes-256-cbc -K $encrypted_8aad19900c29_key -iv $encrypted_8aad19900c29_iv -in tests/testthat/Rinstapkg_test_settings.rds.enc -out tests/testthat/Rinstapkg_test_settings.rds -d
- R -q -e 'install.packages(c("remotes", "curl")); remotes::install_github("ropenscilabs/tic");
  tic::prepare_all_stages(); tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
language: r
sudo: false
dist: trusty
cache: packages
latex: false
matrix:
  include:
  - r: release
    env:
    - BUILD_PKGDOWN: true
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"
  - TRAVIS_CXXFLAGS="-Wall -Wextra -pedantic -Werror"
services: 
